version: "3"

services:
  fibonacci-rabbitmq:
    image: rabbitmq:3-management
    container_name: fibonacci.rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    networks:
      - fibonacci

  fibonacci-service:
    build:
      context: ./
      dockerfile: ServerDocker
    container_name: fibonacci.service
    networks:
      - fibonacci
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7122:7122

networks:
  fibonacci:
    driver: bridge
